### ISSUE TITLE
TUD OAuth doesn't work anymore

### ISSUE THREAD

**Issue by GijsWeterings** [ReadBox/readbox#5]
On logging in with netID, I get redirected to https://oauth.tudelft.nl/OAuth/oauth2/authorize where I get the error message:
> error=invalid_request&error_description=redirect_uri_mismatch

**Comment by WoLpH** [comment]
It's a bit hard for me to reproduce unfortunately, I'm not a student anymore so I don't have a student account :(
Does this happen after logging in with your netid or before?
The steps before work for me but I can't test the rest.

Since it took about 3 months for the TU to finally give me oauth credentials it might just be broken, it doesn't appear to be the most stable/supported system.

**Comment by GijsWeterings** [comment]
It happens as soon as I click the big green button. Both when already logged in on SSO and when logged out. 
I attached a network trace below (censored a few parts of the tokens, don't know how much they are personalized) 
![](https://i.imgur.com/tJfxJD5.jpg)

**Comment by WoLpH** [comment]
Must be some sort of a cookie issue... I have seen it before in the past but I'm not sure what is causing it.And worse, I have no idea what is causing it or how to fix it except for clearing the relevant cookies.

**Comment by GijsWeterings** [comment]
If I try to log in in chrome incognito mode (which shouldn't have access to cookies), I do get the SSO login, but after that it still gives me the same error. Did you change the callback URI by chance? 
> redirect_uri_mismatch

**Comment by WoLpH** [comment]
As far as I know, nothing has changed. Perhaps they require https these
days... ?

I'm not sure if I can do much about it, perhaps I should just use
google-auth instead as the entire TU Delft oauth2 system caused more errors
than it solved.

**Comment by GijsWeterings** [comment]
Maybe reach out to CH connect? https://github.com/wisvch/connect

**Comment by WoLpH** [comment]
That could indeed work, although I don't really have too much time
available these days. For the time being I'm considering simply disabling
removing the netid login and let people register accounts themselves

**Comment by GijsWeterings** [comment]
works for me!

**Comment by WoLpH** [comment]
Done :)
