### ISSUE TITLE
Not receiving password reset mail

### ISSUE THREAD

**Issue by wturk** [ReadBox/readbox#6]
When I enter my mail adress at signup it says 'password reset mail has been sent', but in fact I receive no mail.

**Comment by WoLpH** [comment]
Not sure what to tell you in this case... I can manually reset your password but as far as I can tell the mails have been sent succesfully

![image](https://cloud.githubusercontent.com/assets/270571/18291964/19fa62ce-748b-11e6-8630-6c7f66b9d9e5.png)
![image](https://cloud.githubusercontent.com/assets/270571/18291970/2635c542-748b-11e6-8580-5b11040cedaa.png)

Perhaps the TU mailserver is blocking me for some reason?

**Comment by wturk** [comment]
Is there any possibility to send it to my other mail adress?

**Comment by WoLpH** [comment]
Yes, of course. Just let me know what your mail address is. If you want to keep it private, just send me a mail at wolph<at>wol.ph

**Comment by WoLpH** [comment]
Since the TU mailservers appear to have a few broken spam filters I've removed the requirement for a TU mail address
